export const skills = [
    {name: 'Accounting', value: 5, upgraded: false},
    {name: 'Anthropology', value: 1, upgraded: false},
    {name: 'Appraise', value: 5, upgraded: false},
    {name: 'Archaeology', value: 1, upgraded: false},
    {name: 'Art/Craft', value: 5, upgraded: false},
    {name: 'Charm', value: 15, upgraded: false},
    {name: 'Climb', value: 20, upgraded: false},
    {name: 'Credit Rating', value: 0, upgraded: false},
    {name: 'Cthulhu Mythos', value: 0, upgraded: false},
    {name: 'Disguise', value: 5, upgraded: false},
    {name: 'Dodge', value: 0, upgraded: false},
    {name: 'Drive Auto', value: 20, upgraded: false},
    {name: 'Electric Repair', value: 10, upgraded: false},
    {name: 'Fast Talk', value: 5, upgraded: false},
    {name: 'Fighting (Brawl)', value: 25, upgraded: false},
    {name: 'Firearms (Handgun)', value: 20, upgraded: false},
    {name: 'Firearms (Rifle)', value: 25, upgraded: false},
    {name: 'Firearms (Shotgun)', value: 25, upgraded: false},
    {name: 'First Aid', value: 30, upgraded: false},
    {name: 'History', value: 5, upgraded: false},
    {name: 'Intimidate', value: 15, upgraded: false},
    {name: 'Jump', value: 20, upgraded: false},
    {name: 'Language (Other)', value: 1, upgraded: false},
    {name: 'Language (Own)', value: 0, upgraded: false},
    {name: 'Law', value: 5, upgraded: false},
    {name: 'Library Use', value: 20, upgraded: false},
    {name: 'Listen', value: 20, upgraded: false},
    {name: 'Locksmith', value: 1, upgraded: false},
    {name: 'Mech. Repair', value: 10, upgraded: false},
    {name: 'Medicine', value: 1, upgraded: false},
    {name: 'Natural World', value: 10, upgraded: false},
    {name: 'Navigate', value: 10, upgraded: false},
    {name: 'Occult', value: 5, upgraded: false},
    {name: 'Op. Hv. Machine', value: 1, upgraded: false},
    {name: 'Persuade', value: 10, upgraded: false},
    {name: 'Pilot', value: 1, upgraded: false},
    {name: 'Psychology', value: 10, upgraded: false},
    {name: 'Psychoanalysis', value: 1, upgraded: false},
    {name: 'Ride', value: 5, upgraded: false},
    {name: 'Science', value: 1, upgraded: false},
    {name: 'Sleight of Hand', value: 10, upgraded: false},
    {name: 'Spot Hidden', value: 25, upgraded: false},
    {name: 'Stealth', value: 20, upgraded: false},
    {name: 'Survival', value: 10, upgraded: false},
    {name: 'Swim', value: 20, upgraded: false},
    {name: 'Throw', value: 20, upgraded: false},
    {name: 'Track', value: 10, upgraded: false},
]